### ISSUE TITLE
Error , unable to run it

### ISSUE THREAD

**Issue by samjones3** [kenjij/newrelic_redis_plugin#17]
My system is centos 6.8, ruby 2.3, I get below error.
(Yes, installed dante)
How to resolve?

```
[root@localhost newrelic_redis_plugin-1.0.1]# ./newrelic_redis_agent -d
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
        from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./newrelic_redis_agent:4:in `<main>'
```

**Comment by samjones3** [comment]
nvm, fixed it, installed bundler, etc.
