### ISSUE TITLE
Plugin won't start after upgrading Ubuntu from 14.04 to 16.04.4 LTS

### ISSUE THREAD

**Issue by lauracw100** [kenjij/newrelic_redis_plugin#23]
We're getting the following after after upgrading Ubuntu from 14.04 to 16.04.4 LTS when trying to run the plugin:

```
/opt/newrelic_redis_plugin-1.0.1$ sudo ./newrelic_redis_agent
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler/setup (LoadError)
       from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from ./newrelic_redis_agent:4:in `<main>'

```
Our environment is, using rvm:
ruby 2.4.1

Nothing's changed except for the Ubuntu upgrade.

Tried using irb to manually require bundler/setup and got the following error:
2.4.1 :001 > require 'bundler/setup'
LoadError: cannot load such file -- bundler/setup
       from /home/rc.2000/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from /home/rc.2000/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       from (irb):1
       from /home/rc.2000/.rvm/rubies/ruby-2.4.1/bin/irb:11:in `<main>'
2.4.1 :002 >

Are there any additional steps needed after upgrading the OS?

Thanks!
laura

**Comment by lauracw100** [comment]
Fixed by doing:
gem install bundler
bundle install

seems like bundler isn't part of the rvm
