### ISSUE TITLE
cannot load such file -- bundler/setup

### ISSUE THREAD

**Issue by tillkruss** [kenjij/newrelic_redis_plugin#3]
When I run `./newrelic_redis_agent` I receive the following error

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- bundler/setup (LoadError)
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from ./newrelic_redis_agent:4:in `<main>'
```

**Comment by RJBede** [comment]
Give:
gem bundler install

a try, had similar issues.

**Comment by tillkruss** [comment]
Thanks, installing `bundler` and running `bundle install` solved the issue.
