### ISSUE TITLE
rhel 7 problem

### ISSUE THREAD

**Issue by ved123** [kenjij/newrelic_redis_plugin#9]
Hi,

I have following gems installed:
gem list

**\* LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.10.6)
dante (0.2.0)
io-console (0.4.2)
json (1.7.7)
json_pure (1.6.3)
newrelic_plugin (1.3.1)
psych (2.0.0)
rdoc (4.0.0)
redis (3.2.1)

but when i run ./newrelic_redis_agent i get following output:

./newrelic_redis_agent
/usr/share/gems/gems/json-1.7.7/lib/json.rb:60:in `require': cannot load such file -- json/pure (LoadError)
        from /usr/share/gems/gems/json-1.7.7/lib/json.rb:60:in`rescue in module:JSON'
        from /usr/share/gems/gems/json-1.7.7/lib/json.rb:57:in `<module:JSON>'
        from /usr/share/gems/gems/json-1.7.7/lib/json.rb:54:in`<top (required)>'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding/request.rb:1:in `require'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding/request.rb:1:in`<top (required)>'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding.rb:3:in `require'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding.rb:3:in`<top (required)>'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin.rb:1:in `require'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin.rb:1:in`<top (required)>'
        from ./newrelic_redis_agent:6:in `require'
        from ./newrelic_redis_agent:6:in`<main>'

Please help, I'm stuck

**Comment by ved123** [comment]
same problem with json_pure 1.7.7

**\* LOCAL GEMS ***

bigdecimal (1.2.0)
bundler (1.10.6)
dante (0.2.0)
io-console (0.4.2)
json (1.7.7)
json_pure (1.7.7)
newrelic_plugin (1.3.1)
psych (2.0.0)
rdoc (4.0.0)
redis (3.2.1)
[root@xxxxxx newrelic_redis_plugin-1.0.1]# ./newrelic_redis_agent
/usr/share/gems/gems/json-1.7.7/lib/json.rb:60:in `require': cannot load such file -- json/pure (LoadError)
        from /usr/share/gems/gems/json-1.7.7/lib/json.rb:60:in`rescue in module:JSON'
        from /usr/share/gems/gems/json-1.7.7/lib/json.rb:57:in `<module:JSON>'
        from /usr/share/gems/gems/json-1.7.7/lib/json.rb:54:in`<top (required)>'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding/request.rb:1:in `require'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding/request.rb:1:in`<top (required)>'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding.rb:3:in `require'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_platform_binding.rb:3:in`<top (required)>'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin.rb:1:in `require'
        from /usr/local/share/gems/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin.rb:1:in`<top (required)>'
        from ./newrelic_redis_agent:6:in `require'
        from ./newrelic_redis_agent:6:in`<main>'

**Comment by bbaassssiiee** [comment]
Same problem more than a year later.

**Comment by apicht** [comment]
I've done some troubleshooting on this myself and found the issue is related to the newrelic_plugin gem. Until that is resolved, I have a workaround. My workaround is as follows:

1. Run `gem install json_pure`

2. Edit `Gemfile`, add this line before newrelic_plugin:
`gem "json", ">2.0"`

3. Run `bundle update`

4. `./newrelic_redis_agent` no longer returns errors
